"""pips table

Revision ID: ff964c8576d9
Revises: 5c8f6e247ed6
Create Date: 2018-05-04 09:35:46.914804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff964c8576d9'
down_revision = '5c8f6e247ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fellow', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('fellow_class', sa.Integer(), nullable=True),
    sa.Column('manager', sa.Integer(), nullable=False),
    sa.Column('people_rep', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pips')
    # ### end Alembic commands ###
